# Generated by Django 4.2.4 on 2023-08-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equiposProteccion',
            new_name='EquipoProteccion',
        ),
        migrations.RenameModel(
            old_name='equiposRed',
            new_name='EquipoRed',
        ),
        migrations.RenameModel(
            old_name='equiposTelecontrol',
            new_name='EquipoTelecontrol',
        ),
        migrations.AlterModelOptions(
            name='equipoproteccion',
            options={'verbose_name': 'Equipo de Proteccion', 'verbose_name_plural': 'Equipos de Proteccion'},
        ),
        migrations.AlterModelOptions(
            name='equipored',
            options={'verbose_name': 'Equipo de Red', 'verbose_name_plural': 'Equipos de Red'},
        ),
        migrations.AlterModelOptions(
            name='equipotelecontrol',
            options={'verbose_name': 'Equipo de Telecontrol', 'verbose_name_plural': 'Equipos de Telecontrol'},
        ),
        migrations.RenameField(
            model_name='equipoproteccion',
            old_name='defGW',
            new_name='defGw',
        ),
        migrations.RenameField(
            model_name='equipored',
            old_name='defGW',
            new_name='defGw',
        ),
        migrations.RenameField(
            model_name='equipotelecontrol',
            old_name='defGW',
            new_name='defGw',
        ),
    ]
