# Generated by Django 4.2.4 on 2023-08-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_equiposproteccion_equipoproteccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipoproteccion',
            options={'verbose_name': 'Equipo de Protección', 'verbose_name_plural': 'Equipos de Proteccion'},
        ),
    ]
